// <auto-generated />
using System;
using EquipmentManagement.Infra.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EquipmentManagement.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331005344_SeedEquipment")]
    partial class SeedEquipment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EquipmentManagement.Domain.Entities.Equipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefNumCertificado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefSetor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Equipaments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DataAquisicao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Multímetro Digital",
                            NumeroSerie = "MD-0001",
                            RefNumCertificado = "CERT-001",
                            RefSetor = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            DataAquisicao = new DateTime(2022, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Osciloscópio",
                            NumeroSerie = "OSC-0002",
                            RefNumCertificado = "CERT-002",
                            RefSetor = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            DataAquisicao = new DateTime(2021, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nome = "Fonte de Alimentação",
                            NumeroSerie = "FA-0003",
                            RefNumCertificado = "CERT-003",
                            RefSetor = 3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
